"""Identity, auth and driver KYC tables.

Hand-written, not autogenerated. `alembic revision --autogenerate` does not see
partial indexes or PostGIS spatial indexes and will happily emit a migration
that drops them; on a schema this index-dependent, reading a generated diff
costs more than writing the DDL.

Two notes on things that differ from §5 of the build plan, both explained in
docs/CONTRACT_DECISIONS.md:

  drivers.is_online lives on `drivers`, not on `driver_presence`. §5 wrote
  `CHECK (kyc_status = 'verified' OR NOT is_online)` on `drivers`, but Postgres
  CHECK constraints cannot reference another table, so as specified the
  constraint could not be created at all. Moving the flag makes it a real
  database-enforced invariant: an unverified driver cannot be marked online
  even by a bug in application code.

  vehicles.front_seat_available is new. §5 gave users a `requires_front_seat`
  with no vehicle column to match it against, so that requirement could never
  be satisfied by the Phase 6 matching query.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    user_role = postgresql.ENUM(
        "passenger", "driver", "admin", name="user_role", create_type=False
    )
    user_status = postgresql.ENUM(
        "active", "restricted", "suspended", name="user_status", create_type=False
    )
    kyc_status = postgresql.ENUM(
        "pending",
        "verified",
        "rejected",
        "suspended",
        name="kyc_status",
        create_type=False,
    )

    op.execute("CREATE TYPE user_role AS ENUM ('passenger', 'driver', 'admin')")
    op.execute("CREATE TYPE user_status AS ENUM ('active', 'restricted', 'suspended')")
    op.execute(
        "CREATE TYPE kyc_status AS ENUM ('pending', 'verified', 'rejected', 'suspended')"
    )

    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("phone_e164", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("role", user_role, nullable=False, server_default="passenger"),
        sa.Column("status", user_status, nullable=False, server_default="active"),
        sa.Column("locale", sa.Text(), nullable=False, server_default="fr"),
        # Vehicle capability requirements only. Never a medical or personal
        # attribute: Law 2024/017 prohibits processing health data (I9).
        sa.Column(
            "requires_ramp", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column(
            "requires_boot_space",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "requires_front_seat",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "requires_driver_assist",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "allows_guide_animal",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "prefers_text_contact",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("phone_e164", name="uq_users_phone_e164"),
    )

    op.create_table(
        "otp_challenges",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("phone_e164", sa.Text(), nullable=False),
        # An argon2 hash. Never the code: a four-digit keyspace under a fast
        # hash is a lookup table, and this row is live for five minutes.
        sa.Column("code_hash", sa.Text(), nullable=False),
        sa.Column(
            "attempts", sa.SmallInteger(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column(
            "max_attempts",
            sa.SmallInteger(),
            nullable=False,
            server_default=sa.text("5"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_ip", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index(
        "ix_otp_challenges_phone_expires", "otp_challenges", ["phone_e164", "expires_at"]
    )

    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # SHA-256 of the token. A stolen backup must not be a set of live
        # sessions. Not argon2: the token is 256 bits of server entropy, so
        # there is nothing to brute-force and this is read on every refresh.
        sa.Column("token_hash", sa.String(64), nullable=False),
        # Rotation family. Reuse of a rotated token revokes every token here.
        sa.Column("family_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
    )
    op.create_index("ix_refresh_tokens_family", "refresh_tokens", ["family_id"])
    op.create_index("ix_refresh_tokens_user", "refresh_tokens", ["user_id"])

    op.create_table(
        "drivers",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kyc_status", kyc_status, nullable=False, server_default="pending"),
        sa.Column("kyc_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("kyc_rejection_reason", sa.Text(), nullable=True),
        # A keyed hash, never the CNI number itself. Deduplicates registrations
        # and supports banning a person rather than an account.
        sa.Column("cni_ref_hash", sa.String(64), nullable=True),
        sa.Column("rating_avg", sa.Numeric(3, 2), nullable=True),
        sa.Column(
            "is_online", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column(
            "seats_free", sa.SmallInteger(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column("went_online_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("user_id", name="uq_drivers_user_id"),
        sa.UniqueConstraint("cni_ref_hash", name="uq_drivers_cni_ref_hash"),
        # The KYC gate, enforced by the database rather than only by the
        # handler. Application code can have a bug; this cannot be bypassed.
        sa.CheckConstraint(
            "kyc_status = 'verified' OR NOT is_online",
            name="ck_drivers_online_requires_verified_kyc",
        ),
        sa.CheckConstraint("seats_free BETWEEN 0 AND 8", name="ck_drivers_seats_free"),
    )

    op.create_table(
        "vehicles",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "driver_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("drivers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("plate", sa.Text(), nullable=False),
        sa.Column("make", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=False),
        sa.Column("seats", sa.SmallInteger(), nullable=False),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column(
            "has_ramp", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column(
            "has_boot_space",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        # Not in §5. Added because users.requires_front_seat had no vehicle
        # counterpart, so that requirement could never be matched.
        sa.Column(
            "front_seat_available",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
        sa.Column(
            "driver_assists",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "accepts_guide_animal",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint("seats BETWEEN 1 AND 8", name="ck_vehicles_seats"),
    )
    op.create_index("ix_vehicles_driver", "vehicles", ["driver_id"])

    op.create_table(
        "kyc_documents",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "driver_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("drivers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.Text(), nullable=False),
        # AES-256-GCM ciphertext. A SELECT here yields no identity numbers,
        # which turns a database compromise into an incident rather than a
        # disclosure under Law 2024/017.
        sa.Column("reference_enc", sa.LargeBinary(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index(
        "ix_kyc_documents_driver_kind",
        "kyc_documents",
        ["driver_id", "kind"],
        unique=True,
    )


def downgrade() -> None:
    op.drop_table("kyc_documents")
    op.drop_table("vehicles")
    op.drop_table("drivers")
    op.drop_table("refresh_tokens")
    op.drop_table("otp_challenges")
    op.drop_table("users")
    op.execute("DROP TYPE IF EXISTS kyc_status")
    op.execute("DROP TYPE IF EXISTS user_status")
    op.execute("DROP TYPE IF EXISTS user_role")
