#!/usr/bin/env bash
#
# Pin exact runtime dependency versions into requirements.lock.txt.
#
# The versions are read out of the built API image rather than resolved in a
# throwaway container or a local venv. That guarantees the lock records what the
# image actually shipped, on the right base image and the right architecture,
# and it excludes dev tooling because the image never had any. It also needs no
# bind mount, which on this setup is one less thing to go wrong.
#
# Run after building, then rebuild so the image installs from the lock:
#   docker compose build api && ./scripts/gen_lock.sh && docker compose build api

set -euo pipefail

cd "$(dirname "$0")/.."

IMAGE="${1:-vora-api}"
OUT="requirements.lock.txt"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

if ! docker image inspect "$IMAGE" >/dev/null 2>&1; then
    echo "image '$IMAGE' not found. Build it first: docker compose build api" >&2
    exit 1
fi

{
    echo "# Generated by scripts/gen_lock.sh from the built ${IMAGE} image."
    echo "# Do not edit by hand. Regenerate after changing requirements.txt."
    docker run --rm --entrypoint pip "$IMAGE" freeze
} > "$TMP"

# A lock that installs nothing is worse than no lock: the image builds clean and
# then fails at runtime with a missing executable. Refuse to write one.
count=$(grep -cE '^[A-Za-z0-9]' "$TMP" || true)
if [ "$count" -lt 5 ]; then
    echo "refusing to write a lock with only ${count} packages; something went wrong" >&2
    exit 1
fi

mv "$TMP" "$OUT"
trap - EXIT
echo "wrote ${OUT} (${count} packages)"
