"""Stable error codes.

Part of the frozen §6 contract. A code's spelling and its default HTTP status
are both promises to the mobile client: rename one and you break a shipped app.
Add new codes freely; never repurpose an existing one.

The whole set is declared here at Phase 0, including codes that only become
reachable in later phases, so that the client can build its full error map once.
"""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    # Generic
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    MALFORMED_REQUEST = "MALFORMED_REQUEST"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE"
    REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
    RATE_LIMITED = "RATE_LIMITED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"

    # Authentication and authorization
    UNAUTHENTICATED = "UNAUTHENTICATED"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    FORBIDDEN_ROLE = "FORBIDDEN_ROLE"
    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
    PHONE_NOT_ALLOWED = "PHONE_NOT_ALLOWED"

    # OTP
    OTP_CHALLENGE_NOT_FOUND = "OTP_CHALLENGE_NOT_FOUND"
    OTP_INVALID = "OTP_INVALID"
    OTP_EXPIRED = "OTP_EXPIRED"
    OTP_ATTEMPTS_EXCEEDED = "OTP_ATTEMPTS_EXCEEDED"

    # Refresh tokens
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID"
    REFRESH_TOKEN_REUSED = "REFRESH_TOKEN_REUSED"

    # Quoting
    QUOTE_INVALID = "QUOTE_INVALID"
    QUOTE_EXPIRED = "QUOTE_EXPIRED"
    QUOTE_ALREADY_USED = "QUOTE_ALREADY_USED"
    OUTSIDE_SERVICE_AREA = "OUTSIDE_SERVICE_AREA"

    # Rides
    RIDE_NOT_FOUND = "RIDE_NOT_FOUND"
    RIDE_STATE_CONFLICT = "RIDE_STATE_CONFLICT"
    ACTIVE_RIDE_EXISTS = "ACTIVE_RIDE_EXISTS"
    OUTSTANDING_BALANCE = "OUTSTANDING_BALANCE"
    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT"
    PIN_INVALID = "PIN_INVALID"
    PIN_ATTEMPTS_EXCEEDED = "PIN_ATTEMPTS_EXCEEDED"
    SEATS_UNAVAILABLE = "SEATS_UNAVAILABLE"
    MESSAGE_TEMPLATE_UNKNOWN = "MESSAGE_TEMPLATE_UNKNOWN"

    # Driver and offers
    KYC_NOT_VERIFIED = "KYC_NOT_VERIFIED"
    DRIVER_NOT_ONLINE = "DRIVER_NOT_ONLINE"
    OFFER_NOT_FOUND = "OFFER_NOT_FOUND"
    OFFER_TAKEN = "OFFER_TAKEN"
    OFFER_EXPIRED = "OFFER_EXPIRED"

    # Sharing
    SHARE_TOKEN_INVALID = "SHARE_TOKEN_INVALID"
    SHARE_TOKEN_EXPIRED = "SHARE_TOKEN_EXPIRED"

    # Corridor
    CORRIDOR_NOT_JOINABLE = "CORRIDOR_NOT_JOINABLE"
    DETOUR_CAP_EXCEEDED = "DETOUR_CAP_EXCEEDED"
    DRIVER_CONSENT_REQUIRED = "DRIVER_CONSENT_REQUIRED"

    # Incidents
    INCIDENT_NOT_FOUND = "INCIDENT_NOT_FOUND"


DEFAULT_STATUS: dict[ErrorCode, int] = {
    ErrorCode.NOT_IMPLEMENTED: 501,
    ErrorCode.INTERNAL_ERROR: 500,
    ErrorCode.MALFORMED_REQUEST: 400,
    ErrorCode.VALIDATION_FAILED: 400,
    ErrorCode.REQUEST_TOO_LARGE: 413,
    ErrorCode.REQUEST_TIMEOUT: 504,
    ErrorCode.RATE_LIMITED: 429,
    ErrorCode.DEPENDENCY_UNAVAILABLE: 503,
    ErrorCode.METHOD_NOT_ALLOWED: 405,

    ErrorCode.UNAUTHENTICATED: 401,
    ErrorCode.INVALID_TOKEN: 401,
    ErrorCode.TOKEN_EXPIRED: 401,
    ErrorCode.FORBIDDEN_ROLE: 403,
    ErrorCode.ACCOUNT_SUSPENDED: 403,
    ErrorCode.PHONE_NOT_ALLOWED: 422,

    ErrorCode.OTP_CHALLENGE_NOT_FOUND: 404,
    ErrorCode.OTP_INVALID: 401,
    ErrorCode.OTP_EXPIRED: 401,
    ErrorCode.OTP_ATTEMPTS_EXCEEDED: 429,

    ErrorCode.REFRESH_TOKEN_INVALID: 401,
    ErrorCode.REFRESH_TOKEN_REUSED: 401,

    ErrorCode.QUOTE_INVALID: 400,
    ErrorCode.QUOTE_EXPIRED: 409,
    ErrorCode.QUOTE_ALREADY_USED: 409,
    ErrorCode.OUTSIDE_SERVICE_AREA: 422,

    # Not 403. Never leak the existence of a ride the caller cannot see (I1).
    ErrorCode.RIDE_NOT_FOUND: 404,
    ErrorCode.RIDE_STATE_CONFLICT: 409,
    ErrorCode.ACTIVE_RIDE_EXISTS: 409,
    ErrorCode.OUTSTANDING_BALANCE: 409,
    ErrorCode.IDEMPOTENCY_KEY_REQUIRED: 400,
    ErrorCode.IDEMPOTENCY_KEY_CONFLICT: 409,
    ErrorCode.PIN_INVALID: 403,
    ErrorCode.PIN_ATTEMPTS_EXCEEDED: 429,
    ErrorCode.SEATS_UNAVAILABLE: 409,
    ErrorCode.MESSAGE_TEMPLATE_UNKNOWN: 400,

    ErrorCode.KYC_NOT_VERIFIED: 409,
    ErrorCode.DRIVER_NOT_ONLINE: 409,
    ErrorCode.OFFER_NOT_FOUND: 404,
    ErrorCode.OFFER_TAKEN: 409,
    ErrorCode.OFFER_EXPIRED: 409,

    ErrorCode.SHARE_TOKEN_INVALID: 404,
    ErrorCode.SHARE_TOKEN_EXPIRED: 404,

    ErrorCode.CORRIDOR_NOT_JOINABLE: 409,
    ErrorCode.DETOUR_CAP_EXCEEDED: 422,
    ErrorCode.DRIVER_CONSENT_REQUIRED: 409,

    ErrorCode.INCIDENT_NOT_FOUND: 404,
}
